### PR TITLE
In-memory/persistance enhancements & test coverage

### PR DESCRIPTION
**Pull request by jondavis9898**
Same content as https://github.com/financialforcedev/fflib-apex-common/pull/100.

### CODE REVIEW

**Comment by afawcett** [comment]
Thanks @jondavis9898 👍

**Comment by afawcett** [comment]
@jondavis9898 and @up2go-rsoesemann would one of you be so kind as to do a small write up? If you don't have a blog or place to published i would be happy to guest post it for you. Great work both! 👍

**Comment by jondavis9898** [comment]
@up2go-rsoesemann Would you be able to do the write-up along with readme updates that you're planning on doing?

**Comment by rsoesemann** [comment]
@afawcett I created this issue https://github.com/financialforcedev/fflib-apex-common-builder/issues/3. I will own it but need @jondavis9898 for code examples.

**Pull request merged**
